## FinLoRA Finer — MemorylessAgent on local JSONL test set

runtime:
  max_envs_to_visit: 0
  max_steps_per_episode: 1
  scores_path: scores.jsonl
  run_validation_at_start: true
  validation_num_workers: 100

validation_dataset:
  type: finer
  hf_dataset: "stalaei/finer_test_balanced"
  split: "val"
  input_field: "context"
  target_field: "target"
  instruction_template: null
  max_samples: 1000
  shuffle: false

agent:
  type: memoryless_agent
  lm_config:
    model: "gemini-2.0-flash"
    temperature: 0.0
    max_output_tokens: 8192
    log_calls: true
  system_prompt: "{file:src/data/prompts/finer/system_prompt.txt}"

output:
  results_dir: outputs/finer/memoryless_agent/finer_test_balanced_gemini_2.0_flash
  log_level: INFO