## FinLoRA Finer — MemorylessAgent using Tokasaurus (Llama 3.2 3B Instruct)

runtime:
  max_envs_to_visit: 0
  max_steps_per_episode: 1
  scores_path: scores.jsonl
  run_validation_at_start: true
  validation_num_workers: 100

validation_dataset:
  type: finer
  hf_dataset: "stalaei/finer_test_balanced"
  split: "val"
  input_field: "context"
  target_field: "target"
  instruction_template: null
  max_samples: 1000
  shuffle: false

agent:
  type: memoryless_agent
  lm_config:
    # Use provider-prefixed model to dispatch to Tokasaurus
    model: "toka:meta-llama/Llama-3.2-3B-Instruct"
    temperature: 0.0
    max_output_tokens: 8192
    log_calls: true
    # Tokasaurus-specific fields (present on TokasaurusConfig)
    base_url: "http://localhost:8080"
    stop_sequences: ["FEEDBACK", "OBSERVATION"]
    max_retries: 0

  system_prompt: "{file:src/data/prompts/finer/system_prompt.txt}"

output:
  results_dir: outputs/finer/memoryless_agent/finer_test_balanced_toka_llama3b
  log_level: INFO


