name: continual_learning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.11
  - pip
  - numpy=2.3.3
  - pandas=2.3.3
  - matplotlib=3.10.6
  - pyyaml=6.0.3
  - tqdm=4.67.1
  - requests=2.32.5
  - pillow=11.3.0
  - pyarrow=21.0.0
  - sympy=1.14.0
  - jupyter
  - ipython
  - pip:
    - google-generativeai==0.8.5
    - google-genai==1.39.1
    - datasets==4.1.1
    - huggingface-hub==0.35.3
    - python-dotenv==1.1.1
    - tabulate==0.9.0
    - pydantic==2.11.9
    - fsspec==2025.9.0
    - filelock==3.19.1
    - dill==0.4.0
    - multiprocess==0.70.16
    - xxhash==3.5.0
    - tenacity==9.1.2
    - cachetools==5.5.2
    - protobuf==5.29.5
    - grpcio==1.75.1
    - google-api-core==2.25.1
    - google-auth==2.40.3
    - google-auth-oauthlib==1.2.2
    - google-auth-httplib2==0.2.0
    - google-api-python-client==2.183.0
    - googleapis-common-protos==1.70.0
    - grpcio-status==1.71.2
    - proto-plus==1.26.1
    - aiohttp==3.12.15
    - httpx==0.28.1
    - httpcore==1.0.9
    - websockets==15.0.1
    - aiohappyeyeballs==2.6.1
    - aiosignal==1.4.0
    - anyio==4.11.0
    - attrs==25.3.0
    - charset-normalizer==3.4.3
    - frozenlist==1.7.0
    - h11==0.16.0
    - idna==3.10
    - multidict==6.6.4
    - sniffio==1.3.1
    - yarl==1.20.1
    - certifi==2025.8.3
    - urllib3==2.5.0
    - oauthlib==3.3.1
    - requests-oauthlib==2.0.0
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.2
    - rsa==4.9.1
    - uritemplate==4.2.0
    - httplib2==0.31.0
    - pydantic-core==2.33.2
    - annotated-types==0.7.0
    - typing-inspection==0.4.1
    - contourpy==1.3.3
    - cycler==0.12.1
    - fonttools==4.60.1
    - kiwisolver==1.4.9
    - pyparsing==3.2.5
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - six==1.17.0
    - mpmath==1.3.0
