# Example config for src.datagen.generate (ReplayStrategy)
output_dir: outputs/replay_history_envs
output_format: jsonl

num_threads: 4
max_samples: 1000
num_repeat_samples: 1
save_individual_files: true
include_teacher_messages_texts: true
metadata:
  project: continual-learning

strategy_llm: ${llm}

strategy:
  type: replay
  memory_adapter:
    checkpoint_path: checkpoints/memory
    teacher_template:
      system: "You are a helpful assistant."
      include_actions: true
      include_feedback: true
