runtime:
  max_envs_to_visit: 10
  max_steps_per_episode: 1
  scores_path: scores.jsonl

train_dataset:
  question_field: question
  answer_field: answer
  instruction_template: "Question: {question}\nPut your answer in \\boxed{{}}."
  items:
    - { question: "What is Shayan's family name?", answer: "Talaei", id: 1 }
    - { question: "What is Brad's surname?", answer: "Brown", id: 2 }
    - { question: "What is Shayan's surname?", answer: "Talaei", id: 3 }
  task_type: exact

validation_dataset:
  question_field: question
  answer_field: answer
  instruction_template: "Question: {question}\nPut your answer in \\boxed{{}}."
  items:
    - { question: "What is Shayan's family name?", answer: "Talaei", id: 1 }
    - { question: "What is Brad's surname?", answer: "Brown", id: 2 }
    - { question: "What is Shayan's surname?", answer: "Talaei", id: 3 }
  task_type: exact

agent:
  type: history_agent
  lm_config:
    model: "gemini-2.5-flash"
    temperature: 0.0
    max_output_tokens: 1024
  memory_config:
    _type: history_list
    max_length: 10
  history_k: 5
  system_prompt: "You are a QA assistant."

output:
  results_dir: outputs/toy
  log_level: INFO


