## OMEGA (allenai/omega-explorative) — HistoryAgent

runtime:
  max_envs_to_visit: 20
  max_steps_per_episode: 1
  scores_path: scores.jsonl
  run_validation_at_start: true
  validation_num_workers: 100
  validation_freq: 10

train_dataset:
  hf_dataset: "allenai/omega-explorative"
  hf_subset: "numbertheory_ordered_lte"
  split: "train"
  input_field: "messages"
  target_field: "ground_truth"
  instruction_template: null
  max_samples: 20
  shuffle: false
  seed: 42
  eval_mode: numeric_tol
  eval_tolerance: 1e-6
  expect_boxed: true

validation_dataset:
  hf_dataset: "allenai/omega-explorative"
  hf_subset: "numbertheory_ordered_lte"
  split: "train"
  input_field: "messages"
  target_field: "ground_truth"
  instruction_template: null
  max_samples: 100
  shuffle: false
  seed: 42
  eval_mode: numeric_tol
  eval_tolerance: 1e-6
  expect_boxed: true

agent:
  type: history_agent
  lm_config:
    model: "gemini-2.5-flash"
    temperature: 0.0
    max_output_tokens: 65536
    log_calls: true
  memory_config:
    _type: history_list
    max_length: 2000
  history_k: null # this the number previous history items obs, action, feedback collectively, and not their tuples
  system_prompt: "You are a careful math assistant. Use prior experience when helpful."

output:
  results_dir: outputs/omega/explorative_history_agent/65k_flash
  log_level: INFO


