runtime:
  max_envs_to_visit: 1
  max_steps_per_episode: 50
  verbose: true
  scores_path: scores.jsonl
  validation_freq: 0

train_dataset:
  type: alfworld
  base_config_path: third_party/reflexion/alfworld_runs/base_config.yaml
  split: eval_out_of_distribution
  num_episodes: 1
  prompts_path: src/data/prompts/alfworld/alfworld_3prompts.json
  verbose: true

agent:
  type: reflexion_agent
  verbose: true
  lm_config:
    model: gpt-4o-mini
    temperature: 0.2
    max_output_tokens: 512
    log_calls: true
  # Use HistoryList memory
  memory_config:
    _type: history_list
    max_length: 200
  history_k: 50
  # Reflexion settings
  enable_reflection: true
  reflect_on_failure_only: false
  failure_threshold: 1.0
  max_reflections_in_prompt: 5
  # Task-specific prompts
  agent_system_prompt: |
    You are an embodied household assistant in ALFWorld.
    - Issue one action per turn (e.g., "go to fridge 1", "open drawer 2", "take apple 1 from table 1", "use desklamp 1").
    - You may think using "think: ..." which should not change the environment.
    - Stop repeating the same action if it yields no new observation.
    - Prioritize completing the task with the least number of steps.
  reflection_few_shot_examples: |
    ${file:src/data/prompts/alfworld/reflexion_few_shot_examples.txt}

output:
  results_dir: outputs/alfworld_reflexion
  log_level: INFO


