## OMEGA (allenai/omega-explorative) — MemorylessAgent on first 20 examples

runtime:
  max_envs_to_visit: 0
  max_steps_per_episode: 1
  scores_path: scores.jsonl
  run_validation_at_start: true
  validation_num_workers: 100

train_dataset: null

validation_dataset:
  hf_dataset: "stalaei/omega-explorative-mixed-subset"
  split: "val"
  input_field: "messages"
  target_field: "ground_truth"
  instruction_template: null
  max_samples: 200
  shuffle: false
  seed: 42
  eval_mode: numeric_tol
  eval_tolerance: 1e-6
  expect_boxed: true
  # Ask env to request structured JSON outputs (OmegaAnswerSchema) for better parsing
  output_type: json

agent:
  type: memoryless_agent
  lm_config:
    model: "gemini-2.5-pro"
    temperature: 0.0
    max_output_tokens: 65536
    log_calls: true
  system_prompt: "You are a careful math assistant. It is absolutely essential that you put your final answer in the \\boxed{{}} format—do not forget this, as your answer will not be parsed otherwise. Always clearly present your final answer in \\boxed{{}}."

output:
  results_dir: outputs/omega_mixed_subset/memoryless_agent/65k_pro_2.5
  log_level: INFO


