## OMEGA (allenai/omega-explorative) — HistoryAgent (with checkpointing)

runtime:
  max_envs_to_visit: 500
  max_steps_per_episode: 1
  scores_path: scores.jsonl
  run_validation_at_start: true
  validation_num_workers: 100
  validation_freq: 10
  # Checkpointing
  checkpoint_dir: checkpoints
  checkpoint_every_episodes: 5
  checkpoint_keep_last: 1
  checkpoint_on_start: false
  resume_from: null
  start_episode_index: 0

train_dataset:
  hf_dataset: "stalaei/omega-4cat-8splits-150train-85val"
  split: "arithmetic_list_prime_factors_train" # arithmetic_gcd, arithmetic_list_prime_factors, combinatory_distribution, arithmetic_matrix_rank 
  input_field: "messages"
  target_field: "ground_truth"
  instruction_template: null
  max_samples: null
  shuffle: false
  seed: 42
  eval_mode: numeric_tol
  eval_tolerance: 1e-6
  expect_boxed: true
  # Keep only the first N subsets (by first appearance) and first K samples per subset
  num_subsets: null
  samples_per_subset: null
  # Controls how incorrect answers are explained
  feedback_type: ground_truth_solution

validation_dataset:
  hf_dataset: "stalaei/omega-4cat-8splits-150train-85val"
  split: "arithmetic_list_prime_factors_val" # arithmetic_gcd, arithmetic_list_prime_factors, combinatory_distribution, arithmetic_matrix_rank 
  input_field: "messages"
  target_field: "ground_truth"
  instruction_template: null
  max_samples: null
  shuffle: false
  seed: 42
  eval_mode: numeric_tol
  eval_tolerance: 1e-6
  expect_boxed: true
  # During validation we can also subset deterministically if desired
  num_subsets: null
  samples_per_subset: null
  # During validation, use templated message only
  feedback_type: final_answer

agent:
  type: history_agent
  lm_config:
    model: "gemini-2.0-flash" # "gemini-2.5-flash"
    temperature: 0.0
    max_output_tokens: 8192
    log_calls: true
  memory_config:
    _type: history_list
    max_length: 2000
  history_k: null # number of previous history items (obs/action/feedback collectively)
  system_prompt: "You are a careful math assistant. You will recieve feedback after each action. You should continually learn from the feedback to improve your performance in the subsequent actions. Don't write ACTION: in your answer."

output:
  results_dir: outputs/omega_four_categories_150_train/history_agent_on_arithmetic_list_prime_factors/8k_flash_2.0_with_gt_solution_feedback
  log_level: INFO


