runtime:
  max_envs_to_visit: 20
  max_steps_per_episode: 1

dataset:
  question_field: question
  answer_field: answer
  instruction_template: "Decrypt the following message: {question}\nThink step by step and finally put your answer in \\boxed{{}}. For example, if your answer is 'hello', you should finally output \\boxed{{hello}}."
  task_type: exact
  dataset_path: data/synthetic/encryption/train_100.jsonl

agent:
  type: history_agent
  lm_config:
    model: "gemini-2.5-flash"
    temperature: 0.0
    thinking_budget: 512
    max_output_tokens: 10000
  memory_config:
    _type: history_list
    max_length: null
  history_k: null
  system_prompt: "You are a QA assistant."

output:
  results_dir: outputs/synthetic/encryption
  save_memory_path: outputs/synthetic/encryption/memory.jsonl
  log_level: INFO


