## OMEGA (allenai/omega-explorative) quick reference
# Source: https://huggingface.co/datasets/allenai/omega-explorative/viewer/
#
# Splits (per subset):
# - train: ~1000 rows
# - test_in: ~100 rows
# - test_out: ~50 rows
#
# Column names:
# - id: string (unique id)
# - setting_key: string (subset key, e.g., algebra_func_area)
# - messages: list of chat turns, typically: [{"role": "user", "content": "..."}]
# - ground_truth: string (final answer text, often numeric; sometimes expects \\boxed{})
# - dataset: string (e.g., MATH_EXPLORATIVE)
#
# Subsets (41):
# - algebra_func_area
# - algebra_func_derivative_sign
# - algebra_func_extrema
# - algebra_func_extrema_coords
# - algebra_func_intersection
# - algebra_func_intersection_coords
# - algebra_func_zeros
# - algebra_linear_equation
# - algebra_polynomial_roots
# - arithmetic_gcd
# - arithmetic_list_prime_factors
# - arithmetic_matrix_determinant
# - arithmetic_matrix_eigenvalues
# - arithmetic_matrix_inverse
# - arithmetic_matrix_multiplication
# - arithmetic_matrix_power
# - arithmetic_matrix_rank
# - arithmetic_matrix_svd
# - arithmetic_mixed
# - combinatory_distribution
# - combinatory_pattern_matching
# - combinatory_probability_at_least_n_specific_fixed
# - combinatory_probability_exactly_n_specific_fixed
# - combinatory_probability_no_fixed_points
# - combinatory_probability_no_specific_letter_fixed
# - geometry_basic
# - geometry_circle
# - geometry_perpendicular_intersection
# - geometry_polygon
# - geometry_polygon_chords
# - geometry_polygon_color
# - geometry_polygon_rotation
# - geometry_triangle
# - logic_gridworld_blocked
# - logic_gridworld_knight_move
# - logic_gridworld_rookmove
# - logic_puzzles_grid_chip
# - logic_zebralogic
# - numbertheory_lte_qr
# - numbertheory_ordered_lte
# - numbertheory_qr_sum

runtime:
  max_envs_to_visit: 5
  max_steps_per_episode: 1

dataset:
  hf_dataset: "allenai/omega-explorative"
  hf_subset: "numbertheory_ordered_lte"  # choose any subset from header list
  split: "train"  # train|test_in|test_out
  input_field: "messages"  # allenai schema uses chat messages
  target_field: "ground_truth"  # allenai schema
  instruction_template: null  # message content already includes instruction
  max_samples: 200
  shuffle: false
  seed: 42
  eval_mode: numeric_tol
  eval_tolerance: 1e-6
  expect_boxed: true

agent:
  type: history_agent
  lm_config:
    model: "gemini-2.5-flash"
    temperature: 0.0
    thinking_budget: 256
    max_output_tokens: 4096
  memory_config:
    _type: history_list
    max_length: 2000
  history_k: 20
  system_prompt: "You are a careful math assistant. Use prior experience when helpful."

output:
  results_dir: outputs/omega/explorative_numbertheory_ordered_lte
  save_memory_path: outputs/omega/explorative_numbertheory_ordered_lte/memory.jsonl
  log_level: INFO


